### ISSUE TITLE
Trouble with finding more than 1 duplicates

### ISSUE THREAD

**Issue by Yukti-09** [akcarsten/Duplicate-Finder#1]
Say, I have 100 images. If the 50th image is a duplicate of the 1st image, the hash for the images from 51 to 100 is not being calculated. Multiple duplicates are not being calculated.

**Comment by akcarsten** [comment]
Hi @Yukti-09 can you post the code that you run?

**Comment by Yukti-09** [comment]
Sure!
```
import duplicates as dup

folder_of_interest = '/Users/Yukti/Desktop/Dataset/'
dup.list_all_duplicates(folder_of_interest, to_csv=True, csv_path='/Users/Yukti/Desktop', fastscan=True)
```
Dataset contains 3 images where image1 and image2 are duplicates of each other. The hash for image1 and image2 is generated in the csv file. The hash for image3 is not generated.

**Comment by akcarsten** [comment]
Hi @Yukti-09,
yes this correct. However internally the hash for all images is  calculated but only the hash for the duplicates is written along with their filename into the csv. The csv file only contains the duplicate files, not files that only appear once.

**Comment by Yukti-09** [comment]
Yes, I understood. Sorry for the trouble!
